### ISSUE TITLE
Cleanup: Unmounting volumes for secrets and configmaps

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#12]
I saw that you recently added an unmounting step in `cleanup.yml`, which is nice. I had that issue a few days ago.

However, today I tried to clean up a cluster that had a few deployments with config maps and secrets, and they appear to be mounted separately, so I had to do something like this manually before continuing:

```
anton@node01:~$ sudo umount /var/lib/kubelet/pods/1d8b27bf-02ba-11e9-8e3f-080027281615/volumes/kubernetes.io~secret/nginx-ingress-token-qpwsq
anton@node01:~$ sudo umount /var/lib/kubelet/pods/6d3fb723-03a6-11e9-b379-080027281615/volumes/kubernetes.io~secret/default-token-9wjxq
anton@node01:~$ sudo umount /var/lib/kubelet/pods/eb91be51-02bd-11e9-8e3f-080027281615/volumes/kubernetes.io~secret/default-token-tg277
anton@node01:~$ sudo umount /var/lib/kubelet/pods/0d18545c-03ae-11e9-b379-080027281615/volumes/kubernetes.io~secret/default-token-9wjxq
anton@node01:~$ sudo umount /var/lib/kubelet/pods/0d18545c-03ae-11e9-b379-080027281615/volume-subpaths/config/kibana/0
anton@node01:~$ sudo umount /var/lib/kubelet/pods/6d3fb723-03a6-11e9-b379-080027281615/volume-subpaths/config/elasticsearch/1
```

Do you think it would be possible to find these in `cleanup.yml` and unmount them, in a good way?

**EDIT:** Or is the preferred way to make sure that the cluster is empty before running the cleanup?

**Comment by amimof** [comment]
Maybe we can reuse what `kubeadm reset` is using to unmount drives. Looks to be a shell command.
https://github.com/kubernetes/kubernetes/blob/b6c8ef298ebfceb66422c416f55ab6076b7ff65d/cmd/kubeadm/app/cmd/reset.go#L159

**Comment by anton-johansson** [comment]
Yeah, that looks like it would do the trick. I can try that out next time I'm cleaning up!
