### ISSUE TITLE
Pod security policies

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#31]
I started messing around with pod security policies to easily notice if my containers are running as root (and doing more complex rules of course). I couldn't get it working, and I ended up in this issue: kubernetes/kubernetes#53063

The argument value for `--enable-admission-plugins` is hardcoded in KTRW. What about having it as an Ansible setting, with a default value matching the currently hardcoded value?

Note: I haven't tested if this actually works for me yet, I just stumbled across it. What's your take on this?

**Comment by anton-johansson** [comment]
For follow up:

I've now tested with the added `PodSecurityPolicy` to `--enable-admission-plugins`, and I've got everything working. I might submit a PR to allow setting this through KTRW.

**Comment by amimof** [comment]
I think the `--enable-admission-plugins` should be set to whatever is the default for `kube-apiserver` which is documented [here](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#which-plugins-are-enabled-by-default). 

I think having the possibility of setting it as an Ansible variable may be a good idea. However maybe it would be even better to have the possibility to override **any** arg to kube-apiserver.
