### ISSUE TITLE
Configurable options to API server

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#37]
I'm planning on doing an LDAP-integration for authentication to our cluster, so we can use a detailed permission system. To do this, I need to use aditional options to the API server:
```
--oidc-issuer-url=https://dex.example.com
--oidc-client-id=example-app
--oidc-ca-file=/etc/ssl/certs/openid-ca.pem
--oidc-username-claim=email
--oidc-groups-claim=groups
```

Any idea on how we can add a generic way of adding API-server options?

Maybe some prefixed Ansible variables? Like `kube-apiserver.oidc-issuer-url=https://dex.example.com`?

**Comment by amimof** [comment]
As much as I like the idea of the ability to customise, I think to a certain extent it just adds too much complexity. The goal has always been to keep it simple and leave keep specific configuration away from this project.

**Comment by anton-johansson** [comment]
Yeah, that's fair enough! How would you suggest tweaking the configuration? I'd very much like to keep using KTRW. I could fork this repository, but that feels bad as well.

**Comment by amimof** [comment]
I would include `install.yml` in a top-level playbook that would do stuff before and after running ktrw. Look at `test/main.yml` which does exactly this.

https://github.com/amimof/kubernetes-the-right-way/blob/master/test/main.yml#L109

**Comment by anton-johansson** [comment]
Hmm, that could work. However, that means I have to replicate the service file for kube-apiserver. That could potentially cause conflicts with future versions of KTRW.

I made a small PR with a suggestion that I don't think is too complex and allows very dynamic configuration, in an easy way. What do you think? See #38.

**Comment by anton-johansson** [comment]
Decided to fork the repository after all, and try to keep up with your changes in the future. :)

Closing this!
