### ISSUE TITLE
Error starting the kube-proxy service

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#4]
According to the [kube-proxy.service.j2](../blob/master/roles/kube-proxy/templates/kube-proxy.service.j2#L6) we're running kube-proxy with this command:
```
/usr/local/bin/kube-proxy --config=/etc/kubernetes/config/kube-proxy.yml
```

When I do that I get the following error:
```
F1214 16:56:03.067953   14535 server.go:361] invalid configuration: no configuration has been provided
```

I googled around a bit, and found [this](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#is-the-kube-proxy-working), which shows a different command. If I run this, my kube-proxy runs:
```
/usr/local/bin/kube-proxy --master=https://{{ cluster_hostname }}:{{ cluster_port }} --kubeconfig=/etc/kubernetes/config/kube-proxy.kubeconfig --v=2
```

The above command makes [kube-proxy.yml](../blob/master/roles/kube-proxy/files/kube-proxy.yml) a bit useless. Am I missing something? It's worth noting that I haven't gotten my cluster fully set up yet, so I haven't verified that everything works with the above command. :)

**EDIT:** Probably same issue as kelseyhightower/kubernetes-the-hard-way/issues/391

**Comment by amimof** [comment]
@anton-johansson i can't seem to reproduce this. Does do you have failed tasks after running `install.yml`? What OS are you running on?

**Comment by anton-johansson** [comment]
I'm using Ubuntu Server 18.04 and the same versions of all packages (kube-proxy, kube-apiserver, etc) as this repository has. I haven't used your `install.yml` directly, because I'm trying to understand all the pieces, so I might have messed something up a long the way.

I'll dig a bit deeper and see if I can get the cluster up and running first.

**Comment by anton-johansson** [comment]
Nice catch! However, I think my issue is unrelated. I tested using the master branch of this repository (with the addition of #8) instead of my own custom one and it worked flawlessly.

I'll close this issue for now, but I'll comment here again when once I find what my problem was. :)
