### ISSUE TITLE
Adding/removing etcd nodes

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#43]
I just tried adding and removing masters to my cluster (etcd is running on my master nodes). My plan was to replace my existing three (really bad) masters with three new masters.

I added the servers to the Ansible inventory and just ran the playbook. It didn't turn out the way I expected.

After googling around, I found out that adding new nodes to (and removing from) etcd requires you to use `etcdctl`. So to add nodes, you run (from one of the existing etcd nodes):
```shell
$ etcdctl --cert-file /etc/etcd/pki/etcd.pem --key-file /etc/etcd/pki/etcd-key.pem --ca-file /etc/etcd/pki/ca.pem --endpoints https://127.0.0.1:2379 member add k8s-master-10 https://<ip-address>:2380
```

Then you get some info back that you should use in your service file:
```
  --initial-cluster k8s-master-10=https://<ip-address>:2380,k8s-master-03=https://<ip-address>:2380,k8s-master-02=https://<ip-address>:2380,k8s-master-01=https://<ip-address>:2380
  --initial-cluster-state existing
```

Note the list of initial cluster nodes and also the initial cluster state.

After doing this manually for each node, I could run the Ansible playbook again to tweak the configuratin files so they are equal on all servers. That worked.

Same goes when removing servers. I had to do:
```shell
$ etcdctl --cert-file /etc/etcd/pki/etcd.pem --key-file /etc/etcd/pki/etcd-key.pem --ca-file /etc/etcd/pki/ca.pem --endpoints https://127.0.0.1:2379 member remove <node-id>
```
... before actually shutting them down and excluding them from the cluster.

This requires a bit of manual work (which is just fine, if it is necessary). Do you have any suggestion on how this can be automated in a better way? Or if not, could/should it be documented within KTRW?

**Comment by amimof** [comment]
I haven't really thought of a master/controll-plane scale out in ktrw. Usually you only scale out the nodes. An alternative would be to tear down the cluster and create a new one with additional masters or etcd's

**Comment by anton-johansson** [comment]
Allright, yeah, it's probably not the most common scenario. Our case wasn't really scale out, but rather migrate to better servers. But I guess we can close this for now. :)
