### ISSUE TITLE
kubectl port-forward

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#5]
kelseyhightower/kubernetes-the-hard-way/issues/78

To be able to run `kubectl port-forward`, the package `socat` needs to be installed on the workers. Should it be installed with the playbook from this repository, or should those "additional" things be installed separately?

Port forwarding is mostly done during development I would suppose, so maybe you wouldn't want extra packages in a production environment?

**Comment by amimof** [comment]
Packages and OS specific configuration is handled outside of this project and it's up to the user to decide how and what is installed on the systems.

**Comment by anton-johansson** [comment]
Allright, thanks!
