### ISSUE TITLE
Additional node tools

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#64]
It's probably not KTRW's responsibility, but would it be a good idea to install additional tools on the nodes, if specific parameters are set in the inventory of course?

For example, I feel it would be great to have [`crictl`](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md) installed so it's easier to debug when issues occur. There are maybe other useful tools that could be optional for KTRW.

Again, it's not really KTRW's responsibility. Thoughts?

**Comment by amimof** [comment]
I've also thought of installing `crictl` on the nodes. It has binary releases so its dist independent. Adding it to KTRW is simple enough and is a good idea I think.
